language: python
python: 3.5
sudo: required
dist: trusty
services: docker
osx_image: xcode6.4
env:
  global:
  - RC=rc2
  - VERSION=2.5.0
  - STAGING=https://dist.apache.org/repos/dist/dev/beam/${VERSION}/
  - ZIP_FILE=apache-beam-${VERSION}-python.zip
  - PLAT=x86_64
  - WHEELHOUSE_UPLOADER_USERNAME=apache-beam-travis
  - BUILD_DEPENDS="Cython"
  - TEST_DEPENDS=
matrix:
  exclude:
  - python: 3.5
  include:
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - UNICODE_WIDTH=16
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - PLAT=i686
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - PLAT=i686
    - UNICODE_WIDTH=16
before_install:
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- wget $STAGING/$ZIP_FILE
- unzip $ZIP_FILE
script:
- build_wheel apache-beam-${VERSION} $PLAT
after_success:
- TRAVIS_BUILD_DIR=.
- ls -lh ${TRAVIS_BUILD_DIR}/io/wheelhouse/
deploy:
  provider: gcs
  access_key_id: GOOGVZ6DVJJWJEV3VOXFSBIZ
  secret_access_key:
    secure: gKwvDhRIzyPEwiU2qqfWrmQ/1I8mcPh4pqZgPOpPb3n5R8xwjvV+4xh+F5S/OlIJ3ky3j1FpgSZQGCeTrPvFPuWHiAEtac3+8eBOSK30cGKjSu5XkdzuFhCJB+CxqhiTIlyOZkBI8AMODVh0LvfXCOScYISOedhPsU1WxBdcYmlc+ZgDXfEM9ODroRgTx/s29sPlkuOGkno9R/OOAr3siVGjzY1f7JfLReU8tDolDgA9aH/ug2crmtNQWMEt1EKj412kzJSr/PiMAhi5aIxpVJmEhMt+JBFmaHr/xPDhzadEOJdEdkuEToXwLOkwdfjhQx4SC84YdPRPh1wetdVzQjTjqOjttIHtryVs6zqHwDbjga60gC2w2XccBbo6idnxtb+SFrnktoo+qk1yOdY26MKGZDCucnKhkVypANt3U/ZfS7uLvc+bHZOxoyRxfz5zQ4yhi351TsrwUtrUciHk+933OJumJfyufhB8jeikZQ/2Det7tVp98aKe4Q9ITiIbNGnBJEevFxDf67t8/oPXCTeQ+IoRWR2RS9wenvBVuLT98Ltb6XuQfD+iAugw4NSIV/D0qpCsFakNNyIxosjgR5JMe14rFuqdK/iA9TCVLYwnw2JknlAa5TZHpn9qVNTNAlrhVnRTtwfA/Q2Fgm2Nw2WIcIBH9adgsgWYOxzsOeI=
  bucket: python_wheels
  skip_cleanup: false
  local-dir: ${TRAVIS_BUILD_DIR}/io/wheelhouse/
